#!/bin/bash

cmd=$1
n=$2

if [ "$cmd" == "start" ];then
if [ -f "zoo.running" ];then
	./run_zoo stop $(cat "zoo.running")
	run "zoo.running"
fi

conf_file="zoo.cfg"
echo -e "tickTime=2000\n"\
"dataDir=/home/jianyu/zookeeper-3.4.6/data/\n"\
"clientPort=2182\n"\
"initLimit=10\n"\
"maxClientCnxns=0\n"\
"syncLimit=5\n" > $conf_file

ip_list=("10.22.1.1" "10.22.1.2" "10.22.1.3" "10.22.1.4" "10.22.1.5" "10.22.1.6" "10.22.1.7" "10.22.1.9")

k_list=$(seq $n)

for i in $k_list
do
	echo "server."$i"=""${ip_list[i - 1]}"":2667:3667" >> $conf_file
done

./scp_multi $conf_file zookeeper-3.4.6/conf 7
./run_multi "rm ~/consensus.zoo.log;rm ~/wait.zoo.log" $n
./run_multi "mkdir ~/zookeeper-3.4.6/data" $n
./run_multi "echo \$((\$i + 1)) > ~/zookeeper-3.4.6/data/myid" $n
./run_multi "~/zookeeper-3.4.6/bin/zkServer.sh start" $n -b

sleep 5
leader_ip=${ip_list[0]}
for i in $k_list
do
	status=$(ssh -t jianyu@"${ip_list[i]}" "~/zookeeper-3.4.6/bin/zkServer.sh status"|grep leader|wc -l)
	if [ "$status" == "1" ];then
		leader_ip=${ip_list[i]}
	fi
done
echo "leader ip is "$leader_ip
echo $n > zoo.running
if [ ! -d "result" ];then
mkdir result
fi

if [ ! -d result/$n ];then
mkdir result/$n
fi

log_file="result/"$n"/"$(date +%s)".txt"
log_file=zo.$3.log
rm $log_file
r=$(seq $3)
for g in $r
do
ssh -t jianyu@10.22.1.2 "PYTHONPATH=~/zk-smoketest/lib.linux-x86_64-2.6 LD_LIBRARY_PATH=~/zk-smoketest/lib.linux-x86_64-2.6 ~/zk-smoketest/zk-latencies.py --servers=$leader_ip":2182" --znode_size=64 --znode_count=10000 --synchronous --root_znode=/zk-latencies_2_$g" >> $log_file &
ssh -t jianyu@10.22.1.3 "PYTHONPATH=~/zk-smoketest/lib.linux-x86_64-2.6 LD_LIBRARY_PATH=~/zk-smoketest/lib.linux-x86_64-2.6 ~/zk-smoketest/zk-latencies.py --servers=$leader_ip":2182" --znode_size=64 --znode_count=10000 --synchronous --root_znode=/zk-latencies_3_$g" >> $log_file &
ssh -t jianyu@10.22.1.4 "PYTHONPATH=~/zk-smoketest/lib.linux-x86_64-2.6 LD_LIBRARY_PATH=~/zk-smoketest/lib.linux-x86_64-2.6 ~/zk-smoketest/zk-latencies.py --servers=$leader_ip":2182" --znode_size=64 --znode_count=10000 --synchronous --root_znode=/zk-latencies_4_$g" >> $log_file &
ssh -t jianyu@10.22.1.5 "PYTHONPATH=~/zk-smoketest/lib.linux-x86_64-2.6 LD_LIBRARY_PATH=~/zk-smoketest/lib.linux-x86_64-2.6 ~/zk-smoketest/zk-latencies.py --servers=$leader_ip":2182" --znode_size=64 --znode_count=10000 --synchronous --root_znode=/zk-latencies_5_$g" >> $log_file &
ssh -t jianyu@10.22.1.6 "PYTHONPATH=~/zk-smoketest/lib.linux-x86_64-2.6 LD_LIBRARY_PATH=~/zk-smoketest/lib.linux-x86_64-2.6 ~/zk-smoketest/zk-latencies.py --servers=$leader_ip":2182" --znode_size=64 --znode_count=10000 --synchronous --root_znode=/zk-latencies_6_$g" >> $log_file &
done

#PYTHONPATH=~/zk-smoketest/lib.linux-x86_64-2.6 LD_LIBRARY_PATH=~/zk-smoketest/lib.linux-x86_64-2.6 ~/zk-smoketest/zk-latencies.py --servers=$leader_ip":2182" --znode_size=64 --znode_count=10000 --synchronous --root_znode=/zk-latencies20 &

#PYTHONPATH=~/zk-smoketest/lib.linux-x86_64-2.6 LD_LIBRARY_PATH=~/zk-smoketest/lib.linux-x86_64-2.6 ~/zk-smoketest/zk-latencies.py --servers=$leader_ip":2182" --znode_size=64 --znode_count=10000 --synchronous --root_znode=/zk-latencies21 &

#PYTHONPATH=~/zk-smoketest/lib.linux-x86_64-2.6 LD_LIBRARY_PATH=~/zk-smoketest/lib.linux-x86_64-2.6 ~/zk-smoketest/zk-latencies.py --servers=$leader_ip":2182" --znode_size=64 --znode_count=10000 --synchronous --root_znode=/zk-latencies22 &
rrr=$(seq $(( $3 - 1)))
for g in $rrr
do
PYTHONPATH=~/zk-smoketest/lib.linux-x86_64-2.6 LD_LIBRARY_PATH=~/zk-smoketest/lib.linux-x86_64-2.6 ~/zk-smoketest/zk-latencies.py --servers=$leader_ip":2182" --znode_size=64 --znode_count=10000 --synchronous --root_znode=/zk-latencies_1_$g >> $log_file &
done

PYTHONPATH=~/zk-smoketest/lib.linux-x86_64-2.6 LD_LIBRARY_PATH=~/zk-smoketest/lib.linux-x86_64-2.6 ~/zk-smoketest/zk-latencies.py --servers=$leader_ip":2182" --znode_size=64 --znode_count=10000 --synchronous --root_znode=/zk-latencies_1_10 >> $log_file

sleep 30
./run_zoo stop $n
exit
fi

if [ "$cmd" == "stop" ];then
~/zookeeper-3.4.6/bin/zkServer.sh stop
./run_multi "~/zookeeper-3.4.6/bin/zkServer.sh stop" $n
./run_multi "rm ~/zookeeper-3.4.6/data/ -R" $n -b
rm "zoo.running"
fi


