#!/bin/bash
n=$1

ip_list=("10.22.1.1" "10.22.1.2" "10.22.1.3" "10.22.1.4" "10.22.1.5" "10.22.1.6" "10.22.1.7" "10.22.1.8" "10.22.1.9")

k_list=$(seq $n)
conf_file="paxos.properties"

kill -9 $(pidof java)
rm $conf_file
for i in $k_list
do
	out="process.$(( $i - 1 ))"" = ""${ip_list[i - 1]}"":40021:30001"
	echo $out >> $conf_file
done
echo "" >> $conf_file
cat "paxos.properties.sample" >> $conf_file
./run_multi "rm ~/S-Paxos/paxos.properties" $n
./scp_multi paxos.properties "S-Paxos" $n
./run_multi "rm ~/S-Paxos/jpaxosLogs/ -R" $n
./run_multi "rm ~/consensus.spaxos.log" $n
#./run_multi "cd ~/S-Paxos;~/S-Paxos/hashmap_replica.sh \$i" $n -b
#cd ~/S-Paxos;~/S-Paxos/hashmap_client.sh 1000
#cd ~/spaxos_script
#./run_multi "kill -9 \\\$(pidof java)" $n
#kill -9 $(pidof java)
